// Code generated by shep's wire exporter. DO NOT EDIT.
// Source: crates/shep-channel/src/wire.rs in github.com/shep-pm/shep.

package channel

// Version is the value the shepherd exports as SHEP_CHANNEL_VERSION.
//
// A stamp, not a negotiation. An app can notice a wire it has never
// seen. It cannot ask for a different one.
const Version = "1"

// The kinds carried in every message's "kind" field.
const (
	// KindReady is the child's readiness signal.
	KindReady = "ready"
	// KindMetric is one metric sample from the child.
	KindMetric = "metric"
	// KindActionReply is the child's answer to one action.
	KindActionReply = "action-reply"
	// KindShutdown is the shepherd asking the app to stop.
	KindShutdown = "shutdown"
	// KindAction is the shepherd dispatching one custom action.
	KindAction = "action"
)

// ChildMessage is one line the app writes to the shepherd.
//
// Kind selects which other fields carry meaning. Each of those is a
// pointer. Dropping a zero would lose a metric of 0.
type ChildMessage struct {
	Kind   string   `json:"kind"`
	Name   *string  `json:"name,omitempty"`
	Value  *float64 `json:"value,omitempty"`
	Action *string  `json:"action,omitempty"`
	Body   *string  `json:"body,omitempty"`
	ID     *uint64  `json:"id,omitempty"`
}

// ShepherdMessage is one line the shepherd writes to the app.
//
// Kind selects which other fields carry meaning. An absent Params
// differs from an empty one, so it is a pointer too.
type ShepherdMessage struct {
	Kind   string  `json:"kind"`
	Name   *string `json:"name,omitempty"`
	Params *string `json:"params,omitempty"`
	ID     *uint64 `json:"id,omitempty"`
}
